//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchTarget
    {
        public int BID { get; set; }
        public int DID { get; set; }
        public string District { get; set; }
        public string BranchName { get; set; }
        public decimal Deposit { get; set; }
        public decimal FCY { get; set; }
        public decimal merchant { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual DistrictPlan DistrictPlan { get; set; }
    }
}
