//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckInCheckOut
    {
        public int id { get; set; }
        public string priority_activity { get; set; }
        public string deliverable { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> check_in_date { get; set; }
        public Nullable<int> created_by { get; set; }
        public string district { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual User User { get; set; }
    }
}
