//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepositPlanFinal
    {
        public string UserID { get; set; }
        public string process { get; set; }
        public string District { get; set; }
        public string Branch { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string AccountNumber { get; set; }
        public string ReferenceNumber { get; set; }
        public string RefDate { get; set; }
        public string AccountHolder { get; set; }
        public Nullable<decimal> IntialAccountBalance { get; set; }
        public decimal AccountBalance { get; set; }
        public string Narative { get; set; }
        public string User { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string DepositType { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public Nullable<int> DID { get; set; }
    }
}
