//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepositMerchantAgenet
    {
        public int MID { get; set; }
        public int UserID { get; set; }
        public string Process { get; set; }
        public string District { get; set; }
        public string Branch { get; set; }
        public decimal Target { get; set; }
        public string LinkAccount { get; set; }
        public string AccountNumber { get; set; }
        public string ReferenceNumber { get; set; }
        public string AccountHolder { get; set; }
        public decimal IntialAccountBalance { get; set; }
        public decimal AccountBalance { get; set; }
        public string Merchant_Type { get; set; }
        public string Business_Type { get; set; }
        public string QR { get; set; }
        public string Narative { get; set; }
        public string CreatedBY { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string DepositType { get; set; }
        public Nullable<decimal> Prev_Ini_Bal { get; set; }
    
        public virtual User User { get; set; }
    }
}
