//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepositPlanupdated
    {
        public decimal USERID { get; set; }
        public string PROCESS_ { get; set; }
        public string DISTRICT { get; set; }
        public string BRANCH { get; set; }
        public decimal AMOUNT { get; set; }
        public string ACCOUNTNUMBER { get; set; }
        public string REFERENCENUMBER { get; set; }
        public Nullable<System.DateTime> REFDATE { get; set; }
        public string ACCOUNTHOLDER { get; set; }
        public decimal INTIALACCOUNTBALANCE { get; set; }
        public decimal ACCOUNTBALANCE { get; set; }
        public string NARATIVE { get; set; }
        public string USER_ { get; set; }
        public System.DateTime CREATEDDATE { get; set; }
        public string DEPOSITTYPE { get; set; }
        public Nullable<decimal> BOOKING_DATE { get; set; }
        public string STMT_ENTRY_ID { get; set; }
        public string TRANS_REFERENCE { get; set; }
        public Nullable<decimal> CLOSING_BALANCE { get; set; }
        public Nullable<decimal> PREV_CLOSING_BALANCE { get; set; }
        public decimal DID { get; set; }
    }
}
