//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fcy_Branch
    {
        public int ID { get; set; }
        public decimal FcyTargetAmount { get; set; }
        public string District { get; set; }
        public string Branch { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
