//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerchantAchieved
    {
        public int Achieved_ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UserName { get; set; }
        public string Process { get; set; }
        public string District { get; set; }
        public string Branch { get; set; }
        public string Position { get; set; }
        public Nullable<int> UserTarget { get; set; }
        public Nullable<decimal> CollectedAmount { get; set; }
        public Nullable<int> AchievedMerchant { get; set; }
        public Nullable<decimal> AchievedPercent { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
