//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TRMSEntities : DbContext
    {
        public TRMSEntities()
            : base("name=TRMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountMapping> AccountMappings { get; set; }
        public virtual DbSet<AccountReserve> AccountReserves { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<BranchTarget> BranchTargets { get; set; }
        public virtual DbSet<CheckInCheckOut> CheckInCheckOuts { get; set; }
        public virtual DbSet<DepartementInfo> DepartementInfoes { get; set; }
        public virtual DbSet<DepositFCY> DepositFCies { get; set; }
        public virtual DbSet<DepositMerchantAgenet> DepositMerchantAgenets { get; set; }
        public virtual DbSet<DepositPlan> DepositPlans { get; set; }
        public virtual DbSet<DistrictPlan> DistrictPlans { get; set; }
        public virtual DbSet<ECO> ECOes { get; set; }
        public virtual DbSet<Fcy_Branch> Fcy_Branch { get; set; }
        public virtual DbSet<MerchantAchieved> MerchantAchieveds { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Process> Processes { get; set; }
        public virtual DbSet<Subprocess> Subprocesses { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<UserAchieved> UserAchieveds { get; set; }
        public virtual DbSet<UserEngagement> UserEngagements { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<VariationReport> VariationReports { get; set; }
        public virtual DbSet<DepositPlan_bkp> DepositPlan_bkp { get; set; }
        public virtual DbSet<DepositPlanFinal> DepositPlanFinals { get; set; }
        public virtual DbSet<mnemonicccsv> mnemonicccsvs { get; set; }
    }
}
