//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string UserBranch { get; set; }
        public string Process { get; set; }
        public string ReferenceNumber { get; set; }
        public string CreditAccount { get; set; }
        public string Slip { get; set; }
        public Nullable<decimal> TransactionAmount { get; set; }
        public string TransactionType { get; set; }
        public string Channal { get; set; }
        public string TransctionBranch { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> TranDate { get; set; }
        public string Collected_Type { get; set; }
        public Nullable<int> Particpant_Number { get; set; }
        public Nullable<int> Total_Particpant { get; set; }
        public string Joint1 { get; set; }
        public string Joint2 { get; set; }
        public string Joint3 { get; set; }
        public string Joint4 { get; set; }
        public string Joint5 { get; set; }
        public string Created_By { get; set; }
    }
}
