//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEngagement
    {
        public int id { get; set; }
        public Nullable<int> Contacts { get; set; }
        public Nullable<int> Promise { get; set; }
        public Nullable<int> Deposited { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
    }
}
