//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.CheckInCheckOuts = new HashSet<CheckInCheckOut>();
            this.DepositFCies = new HashSet<DepositFCY>();
            this.DepositMerchantAgenets = new HashSet<DepositMerchantAgenet>();
            this.DepositPlans = new HashSet<DepositPlan>();
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
        public string Password { get; set; }
        public string MailAdress { get; set; }
        public string Process { get; set; }
        public string District { get; set; }
        public string Branch { get; set; }
        public string OrganizatinalUnit { get; set; }
        public string Postion { get; set; }
        public string Role { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<decimal> DepositTargetAmount { get; set; }
        public Nullable<int> MerchantTarget { get; set; }
        public Nullable<decimal> FCYTargetAmount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> BranchDepositTarget { get; set; }
        public Nullable<int> BranchMerchantTarget { get; set; }
        public Nullable<decimal> BranchFcyTarget { get; set; }
        public Nullable<bool> ReportStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckInCheckOut> CheckInCheckOuts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepositFCY> DepositFCies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepositMerchantAgenet> DepositMerchantAgenets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepositPlan> DepositPlans { get; set; }
    }
}
